site_name: "{{project_name}}"
site_description: "{{project_description}}"
docs_dir: docs
site_dir: public

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: Light mode
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - toc.follow

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
